# Generated by Django 3.1.6 on 2021-02-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('associated_date', models.DateTimeField()),
            ],
        ),
    ]
