# Generated by Django 3.1.6 on 2021-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
