# Generated by Django 3.1.6 on 2021-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210210_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
