# Generated by Django 3.1.6 on 2021-02-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoryFun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fruit_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('associated_date', models.DateTimeField(verbose_name='your date here')),
            ],
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
        migrations.AddField(
            model_name='fruit_color',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categoryFun.fruit_name'),
        ),
    ]
